baseURL = 'https://hawc2.github.io/'
languageCode = 'en-us'
title = 'Alex Wermer-Colan'

[params]
  description = "Digital scholarship, translation, pedagogy, and community tech"
  author = "Alex Wermer-Colan"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 2

[[menu.main]]
  name = "Writing"
  url = "/writing/"
  weight = 3

[[menu.main]]
  name = "Dramaturgy"
  url = "/dramaturgy/"
  weight = 4

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 5

[[menu.main]]
  name = "Teaching"
  url = "/pedagogy/"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7
